version: '3.7'

services:

  app:
    image: node:current-alpine3.10
    tty: true
    working_dir: /usr/src/app
    volumes:
      - '.:/usr/src/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
